version: "3.2"

services:
  httpd:
    build:
      context: "."
      dockerfile: "Dockerfile-httpd"
    image: httpd-custom
    container_name: httpd
    ports:
      - "80:80"

  shortestpath:
    build:
      context: "."  
    image: shortestpath
    container_name: shortestpath
    volumes:
      - "${PWD}/test-data-sets/docker/:/data/"
      - unipartitePebbleStore:/pebble/unipartite
      - bipartitePebbleStore:/pebble/bipartite

volumes:
  bipartitePebbleStore:
    external: false

  unipartitePebbleStore:
    external: false