version: "3.2"

services:
  web-app:
    build:
      context: "."
    image: shortestpath
    ports:
      - "8090:8090"
    volumes:
      - "${PWD}/demo-data-sets/docker/:/data/"
      - unipartitePebbleStore:/pebble/unipartite
      - bipartitePebbleStore:/pebble/bipartite
      - signatureStore:/signatureStore

volumes:
  bipartitePebbleStore:
    external: false

  unipartitePebbleStore:
    external: false

  signatureStore:
    external: false
